withme.application.version: v0.0.1

jwt.secret.key: ${JWT_SECRET_KEY}

logging:
  level:
    com.umc.withme: debug
    org.hibernate.SQL: debug

spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

---
# Settings for local(dev)
management.endpoints.web.exposure.include: "*"

spring:
  config.activate.on-profile: local
  datasource:
    url: ${WITHME_LOCAL_DB_URL}
    username: ${WITHME_LOCAL_DB_USERNAME}
    password: ${WITHME_LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: create
    defer-datasource-initialization: true
  sql.init.mode: always

---
# Settings for production(dev-server)
logging:
  level:
    com.umc.withme: info

spring:
  config.activate.on-profile: prod
  datasource:
    url: ${WITHME_PROD_DB_URL}
    username: ${WITHME_PROD_DB_USERNAME}
    password: ${WITHME_PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  sql.init.mode: never

---
# Settings for test
spring:
  config.activate.on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate.ddl-auto: create
    defer-datasource-initialization: true
  sql.init.mode: always
